{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fillpattern
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fillpattern_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fillpattern/fillpattern_{{ version }}.tar.gz
  sha256: 969c242568174673a5bbe8e948e460fa2d1a43a59292e4aa7966a277c358a652

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=3.5
  run:
    - r-base
    - r-ggplot2 >=3.5

test:
  commands:
    - $R -e "library('fillpattern')"           # [not win]
    - "\"%R%\" -e \"library('fillpattern')\""  # [win]

about:
  home: https://cmmr.github.io/fillpattern/, https://github.com/cmmr/fillpattern
  license: MIT
  summary: Adds distinctive yet unobtrusive geometric patterns where solid color fills are normally
    used. Patterned figures look just as professional when viewed by colorblind readers
    or when printed in black and white. The dozen included patterns can be customized
    in terms of scale, rotation, color, fill, line type, and line width. Compatible
    with the 'ggplot2' package as well as 'grid' graphics.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - dansmith01

# Package: fillpattern
# Type: Package
# Title: Patterned Fills for 'ggplot2' and 'grid' Graphics
# Version: 1.0.0
# Date: 2024-03-07
# Authors@R: c( person("Daniel P.", "Smith", , "dansmith01@gmail.com", role  = c("aut", "cre"), comment = c(ORCID = "0000-0002-2479-2044")), person("Alkek Center for Metagenomics and Microbiome Research", role = c("cph", "fnd")) )
# Maintainer: Daniel P. Smith <dansmith01@gmail.com>
# Description: Adds distinctive yet unobtrusive geometric patterns where solid color fills are normally used. Patterned figures look just as professional when viewed by colorblind readers or when printed in black and white. The dozen included patterns can be customized in terms of scale, rotation, color, fill, line type, and line width. Compatible with the 'ggplot2' package as well as 'grid' graphics.
# URL: https://cmmr.github.io/fillpattern/, https://github.com/cmmr/fillpattern
# BugReports: https://github.com/cmmr/fillpattern/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.3.1
# Config/Needs/website: rmarkdown
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# Depends: R (>= 4.2.0)
# Imports: ggplot2 (>= 3.5), grDevices, grid (>= 4.2), methods, utils
# Suggests: ragg, testthat (>= 3.0.0)
# NeedsCompilation: no
# Packaged: 2024-03-08 00:29:05 UTC; Daniel
# Author: Daniel P. Smith [aut, cre] (<https://orcid.org/0000-0002-2479-2044>), Alkek Center for Metagenomics and Microbiome Research [cph, fnd]
# Repository: CRAN
# Date/Publication: 2024-03-08 21:10:05 UTC
